src/cfehome/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView


from django.views.generic import TemplateView

from profiles.views import ProfileFollowToggle, RegisterView, activate_user_view
from menus.views import HomeView

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^restaurants/', include('restaurants.urls', namespace="restaurants")),
    url(r'^items/', include('menus.urls', namespace="menus")),
    url(r'^profile-follow/$', ProfileFollowToggle.as_view(), name="follow"),
    url(r'^u/', include('profiles.urls', namespace="profiles")),
    url(r'^contact/$', TemplateView.as_view(template_name="contact.html"), name="contact"),
    url(r'^about_us/$', TemplateView.as_view(template_name="about.html"), name="about"),
    # account
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^register/$', RegisterView.as_view(), name="register"),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name="activate"),

]

src/menus/urls.py
from django.conf.urls import url

from .views import (
    ItemListView,
    ItemDetailView,
    ItemCreateView,
    ItemUpdateView
)

urlpatterns = [

    url(r'^create$', ItemCreateView.as_view(), name="create"),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name="detail"),
    # url(r'^(?P<pk>\d+)/update$', ItemUpdateView.as_view(), name="update"),
    url(r'$', ItemListView.as_view(), name="list"),
]

src/menus/models.py
from django.db import models

from django.conf import settings
from django.core.urlresolvers import reverse

from restaurants.models import Restaurant
# Create your models here.

class Item(models.Model):
    # associations
    user        = models.ForeignKey(settings.AUTH_USER_MODEL)
    restaurant  = models.ForeignKey(Restaurant)
    # item stuff
    name        = models.CharField(max_length=100)
    contents    = models.TextField(help_text='Separate each item by comma')
    excludes    = models.TextField(
        blank=True, null=True, help_text='Separate each item by comma'
    )
    public      = models.BooleanField(default=True)
    # date
    timestamp   = models.DateTimeField(auto_now_add=True)
    update      = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-update", "-timestamp"]

    def __str__(self):
        return self.name    

    def get_contents(self):
        return self.contents.split(",")

    def get_excludes(self):
        return self.excludes.split(",")

    def get_absolute_url(self):
        return reverse('menus:detail', kwargs={'pk': self.pk})

src/menus/forms.py
from django import forms

from .models import Item
from restaurants.models import Restaurant
# Create your forms here

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = [
            'restaurant',
            'name',
            'contents',
            'excludes',
            'public'
        ]
    def __init__(self, user=None, *args, **kwargs):
        print(user)
        print(kwargs)
        super(ItemForm, self).__init__(*args, **kwargs)
        self.fields['restaurant'].queryset = Restaurant.objects.filter(owner=user)

src/menus/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin

from django.views.generic import View, ListView, DetailView, CreateView, UpdateView

from .forms import ItemForm
from .models import Item
# Create your views here.

class HomeView(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            object_list = Item.objects.filter(public=True).order_by('-timestamp')
            return render(request, "home.html", {"object_list": object_list})

        user = request.user
        is_following_user_ids = [x.user.id for x in user.is_following.all()]
        qs = Item.objects.filter(user__id__in=is_following_user_ids, public=True).order_by("-update")[:10]
        return render(request, "menus/home-feed.html", {'object_list': qs})


class ItemListView(LoginRequiredMixin, ListView):
    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

class ItemDetailView(LoginRequiredMixin, DetailView):
    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

class ItemCreateView(LoginRequiredMixin, CreateView):
    template_name = "form.html"
    form_class = ItemForm

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        return super(ItemCreateView, self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(ItemCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super(ItemCreateView, self).get_context_data(*args, **kwargs)
        context['title'] = "Add Item"
        return context


class ItemUpdateView(LoginRequiredMixin, UpdateView):
    template_name = "menus/detail-update.html"
    form_class = ItemForm

    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super(ItemUpdateView, self).get_context_data(*args, **kwargs)
        context['title'] = "Update Item"
        return context

    def get_form_kwargs(self):
        kwargs = super(ItemUpdateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

src/menus/templates/menus/detail-update.html
{% extends "base.html" %}

{% block title %}
  {{form.instance.title}} | Menus | {{block.super}}
{% endblock %}

{% block content %}
  <h1>Menu Items <small><a href="{% url 'menus:create' %}">Add new</a></small></h1>
  <div class="card">
    <div class="card-header">
      {{ form.instance.name }}
    </div>
    <div class="card-body">
      {% if form.instance.contents %}
        <h3>Contents:</h3>
        <ul>
        {% for item in form.instance.get_contents %}
          <li>{{item}}</li>
        {% endfor %}
        </ul>
      {% endif %}
      {% if form.instance.excludes %}
        <h3>Excludes:</h3>
        <ul>
        {% for item in form.instance.get_excludes %}
          <li>{{item}}</li>
        {% endfor %}
        </ul>
      {% endif %}
    </div>
    <div class="card-footer">
      {{ form.instance.timestamp }} | Update: {{ form.instance.update|timesince }} ago
    </div>
  </div>
  <hr/>
  <h3>Make Changes</h3>
  {% include "snippets/form-snippet.html" with form=form %}
{% endblock %}

{% block scripts %}
  <script type="text/javascript">
    $(document).ready(function(){
      $('select').addClass("form-control")
      $('input').addClass("form-control")
      $('textarea').addClass("form-control")
    })
  </script>
{% endblock %}

src/menus/templates/menus/home-feed.html
{% extends 'base.html' %}

{% block content %}

  <div class='row justify-content-sm-center'>
    <div class='col-sm-6 text-center col-sm-offset-3'>
      <h1>User Following Feed</h1>
      {% for obj in object_list %}
        <div class='card'>
          <div class="card-header">
            <h3>
              <a href='{% url "profiles:detail" username=obj.user.username %}'>
                {{ obj.user.username }}
              </a>
            </h3>
            <h4>{{ obj.name }}</h4>
          </div>
          <div class="card-body">
            <p><a href='{% url "profiles:detail" username=obj.user.username %}?q={{ obj.restaurant.title }}'>{{ obj.restaurant.title }}</a>| <a href='{% url "profiles:detail" username=obj.user.username %}?q={{ obj.restaurant.location }}'>{{ obj.restaurant.location }}</a> | <a href='{% url "profiles:detail" username=obj.user.username %}?q={{ obj.restaurant.category }}'>{{ obj.restaurant.category }}</a></p>
            <p>
            <b>{{ obj.name }}:</b> with
              {% for ing in obj.get_contents %}
                <a href='{% url "profiles:detail" username=obj.user.username %}?q={{ ing}}'>{{ ing}}</a>
              {% endfor %}
            </p>
          </div>
          <div class="card-footer">
            {% if obj.timestamp == obj.update %}
              <strong>Create: </strong><i>{{obj.timestamp}}</i>
            {% else %}
              <strong>Update: </strong><i>{{obj.update}}</i>
            {% endif %}
          </div>
        </div>
        <br><br>
      {% endfor %}
    </div>
  </div>

{% endblock %}

src/menus/templates/menus/item_detail.html
{% extends "base.html" %}

{% block title %}
  Item Detail
{% endblock %}

{% block content %}
    <h1 class="text-center">Item Detail</h1>
    <div class="card">
      <div class="card-header">
        {{object.name}}
      </div>
      <div class="card-body">
        <h4 class="card-title">Location: {{object.restaurant.name}}</h4>
        {% if object.contents %}
        <strong>Content:</strong>
        <ul>
          {% for item in object.get_contents %}
            <li>{{item}}</li>
          {% endfor %}
        </ul>
        {% endif %}
        {% if object.excludes %}
        <strong>Exclude:</strong>
        <ul>
          {% for item in object.get_excludes %}
            <li>{{item}}</li>
          {% endfor %}
        </ul>
        {% endif %}
      </div>
      <div class="card-footer">
        <i><strong>Create: </strong><i>{{object.timestamp}}
        <i><strong>Update: </strong><i>{{object.update}}
      </div>
    </div>

{% endblock %}

src/menus/templates/menus/item_list.html
{% extends "base.html" %}

{% block title %}
  Item List
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-8 col-offset-2">
      <h1 class="text-center">Item list</h1>
      {% for obj in object_list %}
        <div class="card">
          <div class="card-header">
              <h5 class="text-center">
                <a href="{{ obj.get_absolute_url }}">
                  {{obj.name}}
                </a>
              </h5>
          </div>
          <div class="card-body">
            {% if obj.contents %}
            <strong>Content:</strong>
            <ul>
              {% for item in obj.get_contents %}
                <li>{{item}}</li>
              {% endfor %}
            </ul>
            {% endif %}
            {% if obj.excludes %}
            <strong>Exclude:</strong>
            <ul>
              {% for item in obj.get_excludes %}
                <li>{{item}}</li>
              {% endfor %}
            </ul>
            {% endif %}
            <a class="btn btn-primary" href="{{ obj.get_absolute_url }}">Detail</a>
          </div>
          <div class="card-footer">
            <i><strong>Create: </strong><i>{{obj.timestamp}}
            <i><strong>Update: </strong><i>{{obj.update}}
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}