src/cfehome/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView


from django.views.generic import TemplateView

from profiles.views import ProfileFollowToggle, RegisterView, activate_user_view
from menus.views import HomeView

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^restaurants/', include('restaurants.urls', namespace="restaurants")),
    url(r'^items/', include('menus.urls', namespace="menus")),
    url(r'^profile-follow/$', ProfileFollowToggle.as_view(), name="follow"),
    url(r'^u/', include('profiles.urls', namespace="profiles")),
    url(r'^contact/$', TemplateView.as_view(template_name="contact.html"), name="contact"),
    url(r'^about_us/$', TemplateView.as_view(template_name="about.html"), name="about"),
    # account
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^register/$', RegisterView.as_view(), name="register"),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name="activate"),

]

src/menus/urls.py
from django.conf.urls import url

from .views import (
    ItemListView,
    ItemDetailView,
    ItemCreateView,
    ItemUpdateView
)

urlpatterns = [

    url(r'^create$', ItemCreateView.as_view(), name="create"),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name="detail"),
    # url(r'^(?P<pk>\d+)/update$', ItemUpdateView.as_view(), name="update"),
    url(r'$', ItemListView.as_view(), name="list"),
]

src/restaurants/urls.py
from django.conf.urls import url

from .views import (
    RestaurantListView,
    RestaurantDetailView,
    RestaurantCreateView,
    RestaurantUpdateView
)

urlpatterns = [
    url(r'^create$', RestaurantCreateView.as_view(), name="create"),
    # url(r'^(?P<slug>[\w-]+)/edit$', RestaurantUpdateView.as_view(), name="edit"),
    url(r'^(?P<slug>[\w-]+)/$', RestaurantUpdateView.as_view(), name="detail"),
    url(r'$', RestaurantListView.as_view(), name="list"),
]

src/restaurants/models.py
from django.db import models
from django.db.models import Q
from django.db.models.signals import pre_save, post_save

from django.core.urlresolvers import reverse
from django.conf import settings

from .utils import unique_slug_generator
from .validators import validate_category

User = settings.AUTH_USER_MODEL
# Create your models here.
class RestaurantQuerySet(models.query.QuerySet):
    def search(self, query):
        if query:
            print(query)
            return self.filter(
                Q(name__icontains=query)|
                Q(location__icontains=query)|
                Q(location__iexact=query)|
                Q(category__icontains=query)|
                Q(category__iexact=query)|
                Q(item__name__icontains=query)|
                Q(item__contents__icontains=query)
            ).distinct()
        return self


class RestaurantManager(models.Manager):
    def get_queryset(self):
        return RestaurantQuerySet(self.model, using=self._db)

    def search(self, query):
        return self.get_queryset().search(query)


class Restaurant(models.Model):
    owner = models.ForeignKey(User)
    name = models.CharField(max_length=120)
    location = models.CharField(max_length=120, blank=True, null=True)
    category = models.CharField(max_length=120, blank=True, null=True, validators=[validate_category])
    timestamp = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    slug = models.SlugField(blank=True, null=True)

    objects = RestaurantManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("restaurants:detail", kwargs={'slug': self.slug})

    @property
    def title(self):
        return self.name

def rl_pre_save_receiver(sender, instance, *args, **kwargs):
    instance.category = instance.category.capitalize()
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

# def rl_post_save_receiver(sender, instance, created, *args, **kwargs):
#     print("Saved....!!")
#     print(instance.timestamp)
#     if not instance.slug:
#         instance.slug = unique_slug_generator(instance)
#         instance.save()

pre_save.connect(rl_pre_save_receiver, sender=Restaurant)

# post_save.connect(rl_post_save_receiver, sender=Restaurant)

src/restaurants/forms.py
from django import forms

from .models import Restaurant
from .validators import validate_category
# Code here

'''
class RestaurantCreateForm(forms.Form):
    name = forms.CharField()
    location = forms.CharField(required=False)
    category = forms.CharField(required=False)

    def clean_name(self):
        name = self.cleaned_data.get("name")
        if name == "React":
            raise forms.ValidationError("Not a valid name!")
        return name
'''

class RestaurantCreateForm(forms.ModelForm):
    # email = forms.EmailField()
    # category = forms.CharField(required=False, validators=[validate_category])
    class Meta:
        model = Restaurant
        fields = [
            'name',
            'location',
            'category',
        ]

    def clean_name(self):
        name = self.cleaned_data.get("name")
        if name.lower() == 'create':
            raise forms.ValidationError("{} is a not valid name!".format(name))
        return name

    # def clean_email(self):
    #     email = self.cleaned_data.get("email")
    #     if ".edu" in email:
    #         raise forms.ValidationError("We do not accept .edu emails")
    #     return email

src/restaurants/views.py
from django.db.models import Q

from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import RestaurantCreateForm
from .models import Restaurant
# Create your views here.


class RestaurantListView(LoginRequiredMixin, ListView):
    def get_queryset(self):
        return Restaurant.objects.filter(owner=self.request.user)
        # slug = self.kwargs.get("slug")
        # if slug:
        #     queryset = Restaurant.objects.filter(
        #         Q(category__iexact=slug) |
        #         Q(category__icontains=slug)
        #     )
        # else:
        #     queryset = Restaurant.objects.all()
        # return queryset

class RestaurantDetailView(LoginRequiredMixin, DetailView):
    def get_queryset(self):
        return Restaurant.objects.filter(owner=self.request.user)


class RestaurantCreateView(LoginRequiredMixin, CreateView):
    form_class = RestaurantCreateForm
    template_name = 'restaurants/form.html'
    success_url = '/restaurants/'

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.owner = self.request.user
        return super(RestaurantCreateView, self).form_valid(form)

    def get_context_data(self, *args, **kwargs):
        context = super(RestaurantCreateView, self).get_context_data(*args, **kwargs)
        context['title'] = "Add Restaurant"
        return context

class RestaurantUpdateView(LoginRequiredMixin, UpdateView):
    form_class = RestaurantCreateForm
    template_name = 'restaurants/detail-update.html'
    login_url = '/login/'

    def get_queryset(self):
        return Restaurant.objects.filter(owner=self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super(RestaurantUpdateView, self).get_context_data(*args, **kwargs)
        name = self.get_object().name
        context['title'] = "Update Restaurant: {}".format(name)
        return context

src/restaurants/templates/restaurants/detail-update.html
{% extends "base.html" %}

{% block title %}
  {{form.instance.title}} | Restaurant | {{block.super}}
{% endblock %}

{% block content %}
  <h1>{{form.instance.title}} <small>{{ form.instance.category }}</small></h1>
  <p>{{ forms.instance.location }}</p>
  <p>{{ form.instance.timestamp }}, Update: {{ form.instance.update|timesince }} ago</p>
  <hr/>
  <h3>Make Changes</h3>
  {% include "snippets/form-snippet.html" with form=form %}
{% endblock %}

src/restaurants/templates/restaurants/form.html
{% extends "base.html" %}

{% block title %}
  {{ title }} | {{block.super}}
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center text-info">{{title}}</h1>
    </div>
    <div class="col-md-6 col-md-offset-3">
      <form class="form-group" action="." method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" name="button">Submit</button>
      </form>
    </div>
    <div class="col-md-3">
      {% if form.errors.non_field_errors %}
        <div class="alert alert-danger">{{ form.errors.non_field_errors }}</div>
      {% endif %}
    </div>
  </div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
  $(document).ready(function(){
    $("label").addClass("label label-default");
    $("input").addClass("form-control");
    $("button").addClass("btn btn-danger");
  });
</script>
{% endblock %}

src/restaurants/templates/restaurants/restaurant_detail.html
{% extends "base.html" %}

{% block title %}
  Restaurant Detail
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1 class="text-justify text-primary">{{ object.name }} <small>{{ object.category }}</small></h1>
      <p>{{ object.location }}</p>
      <p>{{ object.timestamp }}, Updated: {{ object.update|timesince }} ago</p>
    </div>
  </div>
{% endblock %}

src/restaurants/templates/restaurants/restaurant_list.html
{% extends "base.html" %}

{% block title %}
  My Restaurants
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-8 col-offset-2">
      <h1 class="text-center">My Restaurant <small><a href="{% url 'restaurants:create' %}">Add One</a></small></h1>
      <ul class="list-unstyled">
        {% for obj in object_list %}
          <li class="list-group-item">
            <h5 class="text-center"><a href="{% url 'restaurants:detail' slug=obj.slug %}">{{obj.name}}</a></h5>
            <strong>{{obj.location}}</strong>
            <i>{{obj.category}}</i> <br>
            {{obj.timestamp}}{{obj.update}}
            <a href="{% url 'restaurants:detail' obj.slug %}">Edit</a>
          </li>
        {% empty %}
          <li class="list-item">
            <a href="{% url 'restaurants:create' %}">Add One</a>
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
{% endblock %}