src/cfehome/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView


from django.views.generic import TemplateView

from profiles.views import ProfileFollowToggle, RegisterView, activate_user_view
from menus.views import HomeView

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^restaurants/', include('restaurants.urls', namespace="restaurants")),
    url(r'^items/', include('menus.urls', namespace="menus")),
    url(r'^profile-follow/$', ProfileFollowToggle.as_view(), name="follow"),
    url(r'^u/', include('profiles.urls', namespace="profiles")),
    url(r'^contact/$', TemplateView.as_view(template_name="contact.html"), name="contact"),
    url(r'^about_us/$', TemplateView.as_view(template_name="about.html"), name="about"),
    # account
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^register/$', RegisterView.as_view(), name="register"),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name="activate"),

]

src/menus/urls.py
from django.conf.urls import url

from .views import (
    ItemListView,
    ItemDetailView,
    ItemCreateView,
    ItemUpdateView
)

urlpatterns = [

    url(r'^create$', ItemCreateView.as_view(), name="create"),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name="detail"),
    # url(r'^(?P<pk>\d+)/update$', ItemUpdateView.as_view(), name="update"),
    url(r'$', ItemListView.as_view(), name="list"),
]

src/templates/snippets/css.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
<style media="screen">
  .footer {
    padding: 2.5rem 0;
    color: #999;
    text-align: center;
    background-color: #007bff;
    border-top: .05rem solid #e5e5e5;
  }

  .footer p:last-child {
    margin-bottom: 0;
  }

  .footer a{
    color: #eee;
  }
</style>

src/templates/snippets/footer.html
<footer class="footer">
  <p>
    Blog template build for
    <a href="https://getbootstrap.com">Bootstrap</a>
    by
    <a href="https://linkedin/in/max-klitka/">@Max Cage</a>
  </p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

src/templates/snippets/form-snippet.html
{% if form.errors.non_field_errors %}
{{ form.errors.non_field_errors }}
{% endif %}
<form class="form-group" method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <button type='submit' class="btn btn-dark">Save</button>
</form>

src/templates/snippets/js.html
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

src/templates/snippets/nav.html
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <a class="navbar-brand"  href="/">MyPicky.com</a>
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item"><a class="nav-link"  href="{% url 'home' %}">Home</a></li>
        {% if request.user.is_authenticated %}
        <li class="nav-item"><a class="nav-link" href="{% url 'restaurants:list' %}">Restaurant</a></li>
        <li class="nav-item"><a class="nav-link"  href="{% url 'menus:list' %}">Menus</a></li>
        {% endif %}
        <li class="nav-item"><a class="nav-link"  href="{% url 'contact' %}">Contact</a></li>
        <li class="nav-item"><a class="nav-link"  href="{% url 'about' %}">About US</a></li>
        {% if request.user.is_authenticated %}
          <li class="nav-item text-right"></li>
          <li class="nav-item text-right">
            <a class="nav-link"  href="{% url 'logout' %}">
              LogOut({{request.user.username}})
            </a>
          </li>
        {% else %}
          <li class="nav-item text-right"><a class="nav-link"  href="{% url 'login' %}">Login</a></li>
        {% endif %}
      </ul>
    </div>
  </nav>

src/templates/snippets/sidebar.html
<div class="list-group">
  <button role="button" class="list-group-item active">Cras justo odio</button>
  <button role="button" class="list-group-item">Dapibus ac facilisis in</button>
  <button class="list-group-item">Morbi leo risus</button>
  <button class="list-group-item">Porta ac consectetur ac</button>
  <button class="list-group-item">Vestibulum at eros</button>
</div>